import { Injectable, OnModuleDestroy, OnModuleInit } from '@nestjs/common';
import Redis from 'ioredis';
import { Pool, PoolClient, QueryResultRow } from 'pg';
@Injectable()
export class InfrastructureService implements OnModuleInit, OnModuleDestroy {
  private readonly database = new Pool({ connectionString: process.env.DATABASE_URL });
  async onModuleInit() {
    await this.database.query('CREATE EXTENSION IF NOT EXISTS pgcrypto');
    await this.database.query(`CREATE TABLE IF NOT EXISTS users (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), username VARCHAR(32) NOT NULL UNIQUE, email VARCHAR(255) NOT NULL UNIQUE, password_hash TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), last_login TIMESTAMPTZ)`);
    await this.database.query(`CREATE TABLE IF NOT EXISTS user_sessions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, refresh_token_hash TEXT NOT NULL UNIQUE, expires_at TIMESTAMPTZ NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), revoked_at TIMESTAMPTZ)`);
    await this.database.query('CREATE INDEX IF NOT EXISTS user_sessions_user_id_idx ON user_sessions(user_id)');
    await this.database.query(`CREATE TABLE IF NOT EXISTS items (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), slug VARCHAR(64) NOT NULL UNIQUE, name VARCHAR(80) NOT NULL, description TEXT NOT NULL, category VARCHAR(32) NOT NULL, rarity VARCHAR(16) NOT NULL CHECK (rarity IN ('common', 'uncommon', 'rare', 'epic', 'legendary')), base_sell_value INTEGER NOT NULL CHECK (base_sell_value >= 0), stack_limit INTEGER NOT NULL CHECK (stack_limit BETWEEN 1 AND 9999), tradable BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await this.database.query('CREATE INDEX IF NOT EXISTS items_category_idx ON items(category)');
    await this.database.query(`CREATE TABLE IF NOT EXISTS inventory (user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, item_id UUID NOT NULL REFERENCES items(id) ON DELETE RESTRICT, quantity INTEGER NOT NULL CHECK (quantity > 0), locked_quantity INTEGER NOT NULL DEFAULT 0 CHECK (locked_quantity BETWEEN 0 AND quantity), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), PRIMARY KEY (user_id, item_id))`);
    await this.database.query(`CREATE TABLE IF NOT EXISTS player_currencies (user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE, cash BIGINT NOT NULL DEFAULT 0 CHECK (cash >= 0), fans INTEGER NOT NULL DEFAULT 0 CHECK (fans >= 0), reputation INTEGER NOT NULL DEFAULT 0 CHECK (reputation >= 0), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await this.database.query(`CREATE TABLE IF NOT EXISTS player_actions (user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE, last_write_code_at TIMESTAMPTZ, write_code_actions INTEGER NOT NULL DEFAULT 0)`);
    await this.database.query(`CREATE TABLE IF NOT EXISTS gathering_log (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, action VARCHAR(32) NOT NULL, item_id UUID NOT NULL REFERENCES items(id), quantity INTEGER NOT NULL, cash_awarded INTEGER NOT NULL DEFAULT 0, fans_awarded INTEGER NOT NULL DEFAULT 0, occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await this.database.query('CREATE INDEX IF NOT EXISTS gathering_log_user_id_idx ON gathering_log(user_id, occurred_at DESC)');
    await this.database.query(`CREATE TABLE IF NOT EXISTS recipes (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), slug VARCHAR(64) NOT NULL UNIQUE, name VARCHAR(80) NOT NULL, description TEXT NOT NULL, duration_seconds INTEGER NOT NULL CHECK (duration_seconds BETWEEN 1 AND 86400), output_item_id UUID NOT NULL REFERENCES items(id), output_quantity INTEGER NOT NULL CHECK (output_quantity > 0), active BOOLEAN NOT NULL DEFAULT TRUE)`);
    await this.database.query(`CREATE TABLE IF NOT EXISTS recipe_ingredients (recipe_id UUID NOT NULL REFERENCES recipes(id) ON DELETE CASCADE, item_id UUID NOT NULL REFERENCES items(id), quantity INTEGER NOT NULL CHECK (quantity > 0), PRIMARY KEY (recipe_id, item_id))`);
    await this.database.query(`CREATE TABLE IF NOT EXISTS crafting_jobs (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, recipe_id UUID NOT NULL REFERENCES recipes(id), status VARCHAR(16) NOT NULL DEFAULT 'crafting' CHECK (status IN ('crafting', 'completed')), started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), completes_at TIMESTAMPTZ NOT NULL, completed_at TIMESTAMPTZ)`);
    await this.database.query('CREATE INDEX IF NOT EXISTS crafting_jobs_user_idx ON crafting_jobs(user_id, status, completes_at)');
    await this.database.query(`CREATE TABLE IF NOT EXISTS exploration_locations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), slug VARCHAR(64) NOT NULL UNIQUE, name VARCHAR(80) NOT NULL, description TEXT NOT NULL, duration_seconds INTEGER NOT NULL CHECK (duration_seconds BETWEEN 1 AND 86400), reward_item_id UUID NOT NULL REFERENCES items(id), reward_min_quantity INTEGER NOT NULL CHECK (reward_min_quantity > 0), reward_max_quantity INTEGER NOT NULL CHECK (reward_max_quantity >= reward_min_quantity), active BOOLEAN NOT NULL DEFAULT TRUE)`);
    await this.database.query(`CREATE TABLE IF NOT EXISTS expeditions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, location_id UUID NOT NULL REFERENCES exploration_locations(id), status VARCHAR(16) NOT NULL DEFAULT 'exploring' CHECK (status IN ('exploring', 'completed')), started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), completes_at TIMESTAMPTZ NOT NULL, reward_quantity INTEGER, completed_at TIMESTAMPTZ)`);
    await this.database.query('CREATE INDEX IF NOT EXISTS expeditions_user_idx ON expeditions(user_id, status, completes_at)');
    await this.database.query(`CREATE TABLE IF NOT EXISTS npcs (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), slug VARCHAR(64) NOT NULL UNIQUE, name VARCHAR(80) NOT NULL, role VARCHAR(80) NOT NULL)`);
    await this.database.query(`CREATE TABLE IF NOT EXISTS quests (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), slug VARCHAR(64) NOT NULL UNIQUE, npc_id UUID NOT NULL REFERENCES npcs(id), title VARCHAR(100) NOT NULL, description TEXT NOT NULL, requirement_item_id UUID NOT NULL REFERENCES items(id), requirement_quantity INTEGER NOT NULL CHECK (requirement_quantity > 0), reward_cash INTEGER NOT NULL DEFAULT 0 CHECK (reward_cash >= 0), reward_fans INTEGER NOT NULL DEFAULT 0 CHECK (reward_fans >= 0), reward_reputation INTEGER NOT NULL DEFAULT 0 CHECK (reward_reputation >= 0), active BOOLEAN NOT NULL DEFAULT TRUE)`);
    await this.database.query(`CREATE TABLE IF NOT EXISTS player_quests (user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, quest_id UUID NOT NULL REFERENCES quests(id) ON DELETE CASCADE, completed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), PRIMARY KEY (user_id, quest_id))`);
    await this.database.query(`CREATE TABLE IF NOT EXISTS studio_upgrades (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), slug VARCHAR(64) NOT NULL UNIQUE, name VARCHAR(80) NOT NULL, description TEXT NOT NULL, cost_cash INTEGER NOT NULL CHECK (cost_cash >= 0), bonus_cash INTEGER NOT NULL DEFAULT 0, bonus_fans INTEGER NOT NULL DEFAULT 0)`);
    await this.database.query(`CREATE TABLE IF NOT EXISTS player_studio_upgrades (user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, upgrade_id UUID NOT NULL REFERENCES studio_upgrades(id), purchased_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), PRIMARY KEY (user_id, upgrade_id))`);
    await this.database.query(`CREATE TABLE IF NOT EXISTS player_releases (user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, project_slug VARCHAR(64) NOT NULL, released_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), PRIMARY KEY (user_id, project_slug))`);
  }
  async onModuleDestroy() { await this.database.end(); }
  async query<T extends QueryResultRow>(text: string, values: unknown[] = []) { return this.database.query<T>(text, values); }
  async transaction<T>(callback: (client: PoolClient) => Promise<T>) { const client = await this.database.connect(); try { await client.query('BEGIN'); const result = await callback(client); await client.query('COMMIT'); return result; } catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); } }
  async checkDatabase(): Promise<boolean> { try { await this.database.query('SELECT 1'); return true; } catch { return false; } }
  async checkRedis(): Promise<boolean> { const redis = new Redis(process.env.REDIS_URL ?? 'redis://localhost:6379', { connectTimeout: 1_500, maxRetriesPerRequest: 1, lazyConnect: true }); try { await redis.connect(); return (await redis.ping()) === 'PONG'; } catch { return false; } finally { await redis.quit().catch(() => undefined); } }
}
