import { BadRequestException, Injectable, NotFoundException, OnApplicationBootstrap } from '@nestjs/common';
import type { Expedition, ExplorationLocation } from '@gamedev-idle/contracts';
import { InfrastructureService } from '../infrastructure/infrastructure.service';

type LocationRow = { id: string; slug: string; name: string; description: string; duration_seconds: number; reward_item_slug: string; reward_item_name: string; reward_min_quantity: number; reward_max_quantity: number };
type ExpeditionRow = { id: string; location_name: string; status: 'exploring' | 'completed'; completes_at: Date; reward_item_name: string; reward_quantity: number | null };

@Injectable()
export class ExplorationService implements OnApplicationBootstrap {
  constructor(private readonly infrastructure: InfrastructureService) {}

  async onApplicationBootstrap() {
    await this.infrastructure.query(`INSERT INTO exploration_locations (slug, name, description, duration_seconds, reward_item_id, reward_min_quantity, reward_max_quantity) SELECT 'debug-district', 'Debug District', 'Search a packed test floor for useful code and reproducible issues.', 20, id, 3, 6 FROM items WHERE slug = 'source-code' ON CONFLICT (slug) DO NOTHING`);
    await this.infrastructure.query(`INSERT INTO exploration_locations (slug, name, description, duration_seconds, reward_item_id, reward_min_quantity, reward_max_quantity) SELECT 'pixel-pier', 'Pixel Pier', 'Trade ideas with artists along a neon-lit arcade waterfront.', 45, id, 1, 2 FROM items WHERE slug = 'pixel-art' ON CONFLICT (slug) DO NOTHING`);
    await this.infrastructure.query(`INSERT INTO exploration_locations (slug, name, description, duration_seconds, reward_item_id, reward_min_quantity, reward_max_quantity) SELECT 'audio-alley', 'Audio Alley', 'Follow a late-night jam session to find distinctive sound effects.', 60, id, 1, 1 FROM items WHERE slug = 'sound-effect' ON CONFLICT (slug) DO NOTHING`);
  }

  private location(row: LocationRow): ExplorationLocation { return { id: row.id, slug: row.slug, name: row.name, description: row.description, durationSeconds: row.duration_seconds, reward: { itemSlug: row.reward_item_slug, itemName: row.reward_item_name, minQuantity: row.reward_min_quantity, maxQuantity: row.reward_max_quantity } }; }
  private async findLocation(slug: string) { const result = await this.infrastructure.query<LocationRow>('SELECT l.id, l.slug, l.name, l.description, l.duration_seconds, i.slug AS reward_item_slug, i.name AS reward_item_name, l.reward_min_quantity, l.reward_max_quantity FROM exploration_locations l JOIN items i ON i.id = l.reward_item_id WHERE l.slug = $1 AND l.active = TRUE', [slug]); if (!result.rows[0]) throw new NotFoundException('Exploration location not found.'); return result.rows[0]; }
  async listLocations(): Promise<ExplorationLocation[]> { const result = await this.infrastructure.query<LocationRow>('SELECT l.id, l.slug, l.name, l.description, l.duration_seconds, i.slug AS reward_item_slug, i.name AS reward_item_name, l.reward_min_quantity, l.reward_max_quantity FROM exploration_locations l JOIN items i ON i.id = l.reward_item_id WHERE l.active = TRUE ORDER BY l.duration_seconds'); return result.rows.map((row) => this.location(row)); }
  async start(userId: string, locationSlug: string) { const location = await this.findLocation(locationSlug); return this.infrastructure.transaction(async (client) => { const existing = await client.query('SELECT id FROM expeditions WHERE user_id = $1 AND status = $2 FOR UPDATE', [userId, 'exploring']); if (existing.rows.length) throw new BadRequestException('Finish your current expedition before starting another.'); const result = await client.query<{ id: string; completes_at: Date }>(`INSERT INTO expeditions (user_id, location_id, completes_at) VALUES ($1, $2, NOW() + ($3 * INTERVAL '1 second')) RETURNING id, completes_at`, [userId, location.id, location.duration_seconds]); return { id: result.rows[0].id, locationName: location.name, status: 'exploring' as const, completesAt: result.rows[0].completes_at.toISOString(), rewardItemName: location.reward_item_name, rewardQuantity: null }; }); }
  async listExpeditions(userId: string): Promise<Expedition[]> { const result = await this.infrastructure.query<ExpeditionRow>('SELECT e.id, l.name AS location_name, e.status, e.completes_at, i.name AS reward_item_name, e.reward_quantity FROM expeditions e JOIN exploration_locations l ON l.id = e.location_id JOIN items i ON i.id = l.reward_item_id WHERE e.user_id = $1 ORDER BY e.completes_at DESC LIMIT 20', [userId]); return result.rows.map((row) => ({ id: row.id, locationName: row.location_name, status: row.status, completesAt: row.completes_at.toISOString(), rewardItemName: row.reward_item_name, rewardQuantity: row.reward_quantity })); }
  async claim(userId: string, expeditionId: string) { return this.infrastructure.transaction(async (client) => { const result = await client.query<{ id: string; status: string; completes_at: Date; reward_item_id: string; reward_item_name: string; reward_min_quantity: number; reward_max_quantity: number; stack_limit: number }>('SELECT e.id, e.status, e.completes_at, l.reward_item_id, i.name AS reward_item_name, l.reward_min_quantity, l.reward_max_quantity, i.stack_limit FROM expeditions e JOIN exploration_locations l ON l.id = e.location_id JOIN items i ON i.id = l.reward_item_id WHERE e.id = $1 AND e.user_id = $2 FOR UPDATE', [expeditionId, userId]); const expedition = result.rows[0]; if (!expedition || expedition.status !== 'exploring') throw new NotFoundException('Expedition not found.'); if (expedition.completes_at > new Date()) throw new BadRequestException('This expedition is not complete yet.'); const quantity = expedition.reward_min_quantity + Math.floor(Math.random() * (expedition.reward_max_quantity - expedition.reward_min_quantity + 1)); const inventory = await client.query<{ quantity: number }>(`INSERT INTO inventory AS v (user_id, item_id, quantity) VALUES ($1, $2, $3) ON CONFLICT (user_id, item_id) DO UPDATE SET quantity = v.quantity + EXCLUDED.quantity, updated_at = NOW() WHERE v.quantity + EXCLUDED.quantity <= $4 RETURNING quantity`, [userId, expedition.reward_item_id, quantity, expedition.stack_limit]); if (!inventory.rows[0]) throw new BadRequestException(`${expedition.reward_item_name} has reached its stack limit.`); await client.query('UPDATE expeditions SET status = \'completed\', reward_quantity = $2, completed_at = NOW() WHERE id = $1', [expedition.id, quantity]); return { itemName: expedition.reward_item_name, quantity }; }); }
}
