import { BadRequestException, Injectable, NotFoundException, OnApplicationBootstrap } from '@nestjs/common';
import type { CraftingJob, Recipe, RecipeIngredient } from '@gamedev-idle/contracts';
import { InfrastructureService } from '../infrastructure/infrastructure.service';

type RecipeRow = { id: string; slug: string; name: string; description: string; duration_seconds: number; output_item_slug: string; output_item_name: string; output_quantity: number };
type IngredientRow = { item_slug: string; item_name: string; quantity: number; item_id: string };
type JobRow = { id: string; recipe_name: string; status: 'crafting' | 'completed'; completes_at: Date; duration_seconds: number; output_item_name: string; output_quantity: number };

@Injectable()
export class CraftingService implements OnApplicationBootstrap {
  constructor(private readonly infrastructure: InfrastructureService) {}
  async onApplicationBootstrap() {
    await this.infrastructure.query(`INSERT INTO recipes (slug, name, description, duration_seconds, output_item_id, output_quantity)
      SELECT 'refactor-bundle', 'Refactor Bundle', 'Turn rough code and bug reports into a cleaner design document.', 15, i.id, 1 FROM items i WHERE i.slug = 'design-doc' ON CONFLICT (slug) DO NOTHING`);
    await this.infrastructure.query(`INSERT INTO recipes (slug, name, description, duration_seconds, output_item_id, output_quantity)
      SELECT 'vertical-slice', 'Vertical Slice', 'Assemble core code, art, audio, and planning into a prototype blueprint.', 60, i.id, 1 FROM items i WHERE i.slug = 'prototype-blueprint' ON CONFLICT (slug) DO NOTHING`);
    await this.infrastructure.query(`INSERT INTO recipe_ingredients (recipe_id, item_id, quantity) SELECT r.id, i.id, 5 FROM recipes r JOIN items i ON i.slug = 'source-code' WHERE r.slug = 'refactor-bundle' ON CONFLICT DO NOTHING`);
    await this.infrastructure.query(`INSERT INTO recipe_ingredients (recipe_id, item_id, quantity) SELECT r.id, i.id, 2 FROM recipes r JOIN items i ON i.slug = 'bug-report' WHERE r.slug = 'refactor-bundle' ON CONFLICT DO NOTHING`);
    await this.infrastructure.query(`INSERT INTO recipe_ingredients (recipe_id, item_id, quantity) SELECT r.id, i.id, 12 FROM recipes r JOIN items i ON i.slug = 'source-code' WHERE r.slug = 'vertical-slice' ON CONFLICT DO NOTHING`);
    await this.infrastructure.query(`INSERT INTO recipe_ingredients (recipe_id, item_id, quantity) SELECT r.id, i.id, 2 FROM recipes r JOIN items i ON i.slug = 'design-doc' WHERE r.slug = 'vertical-slice' ON CONFLICT DO NOTHING`);
    await this.infrastructure.query(`INSERT INTO recipe_ingredients (recipe_id, item_id, quantity) SELECT r.id, i.id, 2 FROM recipes r JOIN items i ON i.slug = 'pixel-art' WHERE r.slug = 'vertical-slice' ON CONFLICT DO NOTHING`);
    await this.infrastructure.query(`INSERT INTO recipe_ingredients (recipe_id, item_id, quantity) SELECT r.id, i.id, 1 FROM recipes r JOIN items i ON i.slug = 'sound-effect' WHERE r.slug = 'vertical-slice' ON CONFLICT DO NOTHING`);
  }
  private recipe(row: RecipeRow, ingredients: RecipeIngredient[]): Recipe { return { id: row.id, slug: row.slug, name: row.name, description: row.description, durationSeconds: row.duration_seconds, output: { itemSlug: row.output_item_slug, itemName: row.output_item_name, quantity: row.output_quantity }, ingredients }; }
  private async ingredients(recipeId: string) { const result = await this.infrastructure.query<IngredientRow>('SELECT i.slug AS item_slug, i.name AS item_name, ri.quantity, i.id AS item_id FROM recipe_ingredients ri JOIN items i ON i.id = ri.item_id WHERE ri.recipe_id = $1 ORDER BY i.slug', [recipeId]); return result.rows; }
  private async findRecipe(slug: string) { const result = await this.infrastructure.query<RecipeRow>('SELECT r.id, r.slug, r.name, r.description, r.duration_seconds, output_item.slug AS output_item_slug, output_item.name AS output_item_name, r.output_quantity FROM recipes r JOIN items output_item ON output_item.id = r.output_item_id WHERE r.slug = $1 AND r.active = TRUE', [slug]); if (!result.rows[0]) throw new NotFoundException('Recipe not found.'); return result.rows[0]; }
  async listRecipes() { const result = await this.infrastructure.query<RecipeRow>('SELECT r.id, r.slug, r.name, r.description, r.duration_seconds, output_item.slug AS output_item_slug, output_item.name AS output_item_name, r.output_quantity FROM recipes r JOIN items output_item ON output_item.id = r.output_item_id WHERE r.active = TRUE ORDER BY r.duration_seconds'); return Promise.all(result.rows.map(async (row) => this.recipe(row, (await this.ingredients(row.id)).map(({ item_slug, item_name, quantity }) => ({ itemSlug: item_slug, itemName: item_name, quantity })) ))); }
  async start(userId: string, recipeSlug: string) { const recipe = await this.findRecipe(recipeSlug); const ingredients = await this.ingredients(recipe.id); return this.infrastructure.transaction(async (client) => {
      for (const ingredient of ingredients) { const inventory = await client.query<{ quantity: number; locked_quantity: number }>('SELECT quantity, locked_quantity FROM inventory WHERE user_id = $1 AND item_id = $2 FOR UPDATE', [userId, ingredient.item_id]); const owned = inventory.rows[0]; if (!owned || owned.quantity - owned.locked_quantity < ingredient.quantity) throw new BadRequestException(`Not enough unlocked ${ingredient.item_name}.`); const remaining = owned.quantity - ingredient.quantity; if (remaining === 0) await client.query('DELETE FROM inventory WHERE user_id = $1 AND item_id = $2', [userId, ingredient.item_id]); else await client.query('UPDATE inventory SET quantity = $3, updated_at = NOW() WHERE user_id = $1 AND item_id = $2', [userId, ingredient.item_id, remaining]); }
      const job = await client.query<{ id: string; completes_at: Date }>(`INSERT INTO crafting_jobs (user_id, recipe_id, completes_at) VALUES ($1, $2, NOW() + ($3 * INTERVAL '1 second')) RETURNING id, completes_at`, [userId, recipe.id, recipe.duration_seconds]);
      return { id: job.rows[0].id, recipeName: recipe.name, status: 'crafting' as const, completesAt: job.rows[0].completes_at.toISOString(), durationSeconds: recipe.duration_seconds, outputItemName: recipe.output_item_name, outputQuantity: recipe.output_quantity };
    }); }
  async listJobs(userId: string): Promise<CraftingJob[]> { const result = await this.infrastructure.query<JobRow>('SELECT j.id, r.name AS recipe_name, j.status, j.completes_at, r.duration_seconds, i.name AS output_item_name, r.output_quantity FROM crafting_jobs j JOIN recipes r ON r.id = j.recipe_id JOIN items i ON i.id = r.output_item_id WHERE j.user_id = $1 ORDER BY j.completes_at DESC LIMIT 20', [userId]); return result.rows.map((row) => ({ id: row.id, recipeName: row.recipe_name, status: row.status, completesAt: row.completes_at.toISOString(), durationSeconds: row.duration_seconds, outputItemName: row.output_item_name, outputQuantity: row.output_quantity })); }
  async claim(userId: string, jobId: string) { return this.infrastructure.transaction(async (client) => { const result = await client.query<{ id: string; status: string; completes_at: Date; output_item_id: string; output_quantity: number; output_name: string; stack_limit: number }>('SELECT j.id, j.status, j.completes_at, r.output_item_id, r.output_quantity, i.name AS output_name, i.stack_limit FROM crafting_jobs j JOIN recipes r ON r.id = j.recipe_id JOIN items i ON i.id = r.output_item_id WHERE j.id = $1 AND j.user_id = $2 FOR UPDATE', [jobId, userId]); const job = result.rows[0]; if (!job || job.status !== 'crafting') throw new NotFoundException('Crafting job not found.'); if (job.completes_at > new Date()) throw new BadRequestException('This craft is not complete yet.'); const inventory = await client.query<{ quantity: number }>(`INSERT INTO inventory AS v (user_id, item_id, quantity) VALUES ($1, $2, $3) ON CONFLICT (user_id, item_id) DO UPDATE SET quantity = v.quantity + EXCLUDED.quantity, updated_at = NOW() WHERE v.quantity + EXCLUDED.quantity <= $4 RETURNING quantity`, [userId, job.output_item_id, job.output_quantity, job.stack_limit]); if (!inventory.rows[0]) throw new BadRequestException(`${job.output_name} has reached its stack limit.`); await client.query('UPDATE crafting_jobs SET status = \'completed\', completed_at = NOW() WHERE id = $1', [job.id]); return { itemName: job.output_name, quantity: job.output_quantity }; }); }
}
