import { Module } from '@nestjs/common';
import { AuthController } from './auth/auth.controller';
import { AuthService } from './auth/auth.service';
import { HealthController } from './health/health.controller';
import { InfrastructureService } from './infrastructure/infrastructure.service';
import { ItemsController } from './items/items.controller';
import { ItemsService } from './items/items.service';
import { InventoryController } from './inventory/inventory.controller';
import { InventoryService } from './inventory/inventory.service';
import { CurrenciesController } from './currencies/currencies.controller';
import { CurrenciesService } from './currencies/currencies.service';
import { GatheringController } from './gathering/gathering.controller';
import { GatheringService } from './gathering/gathering.service';
import { DashboardController } from './dashboard/dashboard.controller';
import { DashboardService } from './dashboard/dashboard.service';
import { CraftingController } from './crafting/crafting.controller';
import { CraftingService } from './crafting/crafting.service';
import { ExplorationController } from './exploration/exploration.controller';
import { ExplorationService } from './exploration/exploration.service';
import { QuestsController } from './quests/quests.controller';
import { QuestsService } from './quests/quests.service';
import { StudioController } from './studio/studio.controller';
import { StudioService } from './studio/studio.service';
import { MarketController } from './market/market.controller';
import { MarketService } from './market/market.service';
import { ProjectsController } from './projects/projects.controller';
import { ProjectsService } from './projects/projects.service';
@Module({ controllers: [HealthController, AuthController, ItemsController, InventoryController, CurrenciesController, GatheringController, DashboardController, CraftingController, ExplorationController, QuestsController, StudioController, MarketController, ProjectsController], providers: [InfrastructureService, AuthService, ItemsService, InventoryService, CurrenciesService, GatheringService, DashboardService, CraftingService, ExplorationService, QuestsService, StudioService, MarketService, ProjectsService] })
export class AppModule {}
