import { BadRequestException, Injectable, NotFoundException, OnApplicationBootstrap } from '@nestjs/common';
import type { Quest } from '@gamedev-idle/contracts';
import type { QueryResultRow } from 'pg';
import { InfrastructureService } from '../infrastructure/infrastructure.service';

type QuestRow = { id: string; slug: string; title: string; description: string; npc_name: string; npc_role: string; requirement_item_name: string; requirement_quantity: number; reward_cash: number; reward_fans: number; reward_reputation: number; completed_at: Date | null; owned_quantity: number };
type Queryable = { query<T extends QueryResultRow>(text: string, values?: unknown[]): Promise<{ rows: T[] }> };

@Injectable()
export class QuestsService implements OnApplicationBootstrap {
  constructor(private readonly infrastructure: InfrastructureService) {}
  async onApplicationBootstrap() {
    for (const npc of [{ slug: 'mira', name: 'Mira Vale', role: 'Code mentor' }, { slug: 'lena', name: 'Lena Ortiz', role: 'Art director' }, { slug: 'rune', name: 'Rune Park', role: 'Indie producer' }]) await this.infrastructure.query('INSERT INTO npcs (slug, name, role) VALUES ($1, $2, $3) ON CONFLICT (slug) DO NOTHING', [npc.slug, npc.name, npc.role]);
    await this.seedQuest('first-commit', 'mira', 'First Commit', 'Mira wants proof that your studio can turn focus into working code.', 'source-code', 5, 25, 5, 1);
    await this.seedQuest('portfolio-spark', 'lena', 'Portfolio Spark', 'Lena needs a polished asset before introducing you to her artist network.', 'pixel-art', 1, 60, 10, 2);
    await this.seedQuest('vertical-demo', 'rune', 'Vertical Demo', 'Rune is ready to pitch your studio once you can show a complete prototype blueprint.', 'prototype-blueprint', 1, 250, 50, 10);
  }
  private async seedQuest(slug: string, npcSlug: string, title: string, description: string, itemSlug: string, quantity: number, cash: number, fans: number, reputation: number) { await this.infrastructure.query(`INSERT INTO quests (slug, npc_id, title, description, requirement_item_id, requirement_quantity, reward_cash, reward_fans, reward_reputation) SELECT $1, n.id, $3, $4, i.id, $6, $7, $8, $9 FROM npcs n JOIN items i ON i.slug = $5 WHERE n.slug = $2 ON CONFLICT (slug) DO NOTHING`, [slug, npcSlug, title, description, itemSlug, quantity, cash, fans, reputation]); }
  private map(row: QuestRow): Quest { return { slug: row.slug, title: row.title, description: row.description, npcName: row.npc_name, npcRole: row.npc_role, requirement: { itemName: row.requirement_item_name, quantity: row.requirement_quantity }, rewards: { cash: row.reward_cash, fans: row.reward_fans, reputation: row.reward_reputation }, status: row.completed_at ? 'completed' : 'available', claimable: !row.completed_at && row.owned_quantity >= row.requirement_quantity }; }
  private async find(userId: string, slug?: string, client: Queryable = this.infrastructure) { const query = `SELECT q.id, q.slug, q.title, q.description, n.name AS npc_name, n.role AS npc_role, i.name AS requirement_item_name, q.requirement_quantity, q.reward_cash, q.reward_fans, q.reward_reputation, pq.completed_at, COALESCE(inv.quantity, 0) AS owned_quantity FROM quests q JOIN npcs n ON n.id = q.npc_id JOIN items i ON i.id = q.requirement_item_id LEFT JOIN player_quests pq ON pq.quest_id = q.id AND pq.user_id = $1 LEFT JOIN inventory inv ON inv.item_id = q.requirement_item_id AND inv.user_id = $1 WHERE q.active = TRUE ${slug ? 'AND q.slug = $2' : ''} ORDER BY q.reward_reputation`; const result = await client.query<QuestRow>(query, slug ? [userId, slug] : [userId]); return result.rows; }
  async list(userId: string) { return (await this.find(userId)).map((row) => this.map(row)); }
  async claim(userId: string, slug: string) { return this.infrastructure.transaction(async (client) => { const row = (await this.find(userId, slug, client))[0]; if (!row) throw new NotFoundException('Quest not found.'); if (row.completed_at) throw new BadRequestException('Quest reward has already been claimed.'); if (row.owned_quantity < row.requirement_quantity) throw new BadRequestException(`Bring ${row.requirement_quantity} ${row.requirement_item_name} to complete this quest.`); await client.query('INSERT INTO player_quests (user_id, quest_id) SELECT $1, id FROM quests WHERE slug = $2', [userId, slug]); await client.query('INSERT INTO player_currencies (user_id) VALUES ($1) ON CONFLICT (user_id) DO NOTHING', [userId]); await client.query('UPDATE player_currencies SET cash = cash + $2, fans = fans + $3, reputation = reputation + $4, updated_at = NOW() WHERE user_id = $1', [userId, row.reward_cash, row.reward_fans, row.reward_reputation]); return { title: row.title, rewards: { cash: row.reward_cash, fans: row.reward_fans, reputation: row.reward_reputation } }; }); }
}
